# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vidraria', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidraria.Vidraria')),
            ],
        ),
    ]
