# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riscos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classes', models.CharField(max_length=200)),
                ('Subclasses', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Riscos',
            },
        ),
    ]
