# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Fantasia', models.CharField(max_length=200)),
                ('CNPJ', models.CharField(max_length=200)),
                ('Endereço', models.CharField(max_length=200)),
                ('Entrega', models.CharField(max_length=200)),
                ('Atraso', models.CharField(max_length=200)),
                ('Pagamento', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Observação', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
