# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(max_length=200)),
                ('Disciplina', models.CharField(max_length=200)),
            ],
        ),
    ]
