# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vidraria', '__first__'),
        ('Reagente', '__first__'),
        ('Unidade', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.CharField(max_length=200)),
                ('Reagente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reagente.Reagente')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidade.Unidade')),
                ('Vidraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidraria.Vidraria')),
            ],
            options={
                'verbose_name_plural': 'Devolucao',
            },
        ),
    ]
