# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidade', '__first__'),
        ('Fornecedores', '0001_initial'),
        ('Vidraria', '__first__'),
        ('Periodo', '0001_initial'),
        ('Reagente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle_de_Validade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=200)),
                ('Ordenar', models.CharField(max_length=200)),
                ('Dias', models.CharField(max_length=200)),
                ('Validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao_de_Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pratica', models.CharField(max_length=200)),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Periodo.Periodo')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidade.Unidade')),
            ],
            options={
                'verbose_name_plural': 'Devolucao_de_Produtos',
            },
        ),
        migrations.CreateModel(
            name='Ficha_Cardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.DateField()),
                ('Reagente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reagente.Reagente')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fornecedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fornecedores.Fornecedores')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Livro_de_Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_de_Inicio', models.DateField()),
                ('Data_Final', models.DateField()),
                ('Reagente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reagente.Reagente')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidade.Unidade')),
                ('Vidraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidraria.Vidraria')),
            ],
        ),
        migrations.CreateModel(
            name='Ultimas_Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_de_Inicio', models.DateField()),
                ('Data_Final', models.DateField()),
                ('Reagente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reagente.Reagente')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidade.Unidade')),
                ('Vidraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidraria.Vidraria')),
            ],
            options={
                'verbose_name_plural': 'Ultimas_Compras',
            },
        ),
    ]
