# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidade', '__first__'),
        ('Armazenamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produto', models.CharField(max_length=200)),
                ('Grau_de_Pureza', models.CharField(max_length=200)),
                ('Valor_Comercial', models.CharField(max_length=200)),
                ('Classe', models.CharField(max_length=200)),
                ('Quantidade_Disponivel', models.CharField(max_length=200)),
                ('Validade', models.DateField()),
                ('Tipo_de_Armazenamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazenamento.Armazenamento')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidade.Unidade')),
            ],
        ),
    ]
